version: 1.0.{build}

environment:
  global:
    WARNINGS_ARE_ERRORS: 1

  matrix:
  - R_VERSION: devel
    GCC_PATH: mingw_32

  - R_VERSION: devel
    R_ARCH: x64
    GCC_PATH: mingw_64

  - R_VERSION: release
    R_ARCH: x64

  - R_VERSION: stable

build:
  - make clean TYPE=Release